# Generated by Django 3.2.25 on 2024-09-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
