# Generated by Django 3.2.25 on 2024-11-07 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0003_auto_20241004_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_goods', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
    ]
