
DATABASE = {
    'categories': [
        {'id': 1, 'name': 'Fruits', 'slug': 'fruits'},
        {'id': 2, 'name': 'Vegetables', 'slug': 'vegetables'},
        {'id': 3, 'name': 'Meat', 'slug': 'meat'},
        {'id': 4, 'name': 'Fish', 'slug': 'fish'},
        {'id': 5, 'name': 'Dairy', 'slug': 'dairy'},
        {'id': 6, 'name': 'Bakery', 'slug': 'bakery'},
        {'id': 7, 'name': 'Sweets', 'slug': 'sweets'},
        {'id': 8, 'name': 'Drinks', 'slug': 'drinks'},
        {'id': 9, 'name': 'Alcohol', 'slug': 'alcohol'},
        {'id': 10, 'name': 'Tobacco', 'slug': 'tobacco'},
    ],
    'goods': [
        {'id': 1, 'name': 'Apple', 'category_id': 1},
        {'id': 2, 'name': 'Banana', 'category_id': 1},
        {'id': 3, 'name': 'Carrot', 'category_id': 2},
        {'id': 4, 'name': 'Potato', 'category_id': 2},
        {'id': 5, 'name': 'Pork', 'category_id': 3},
        {'id': 6, 'name': 'Beef', 'category_id': 3},
        {'id': 7, 'name': 'Salmon', 'category_id': 4},
        {'id': 8, 'name': 'Tuna', 'category_id': 4},
        {'id': 9, 'name': 'Milk', 'category_id': 5},
        {'id': 10, 'name': 'Cheese', 'category_id': 5},
        {'id': 11, 'name': 'Bread', 'category_id': 6},
        {'id': 12, 'name': 'Cake', 'category_id': 7},
        {'id': 13, 'name': 'Water', 'category_id': 8},
        {'id': 14, 'name': 'Juice', 'category_id': 8},
        {'id': 15, 'name': 'Beer', 'category_id': 9},
        {'id': 16, 'name': 'Wine', 'category_id': 9},
        {'id': 17, 'name': 'Cigarettes', 'category_id': 10},
    ],
}
